# Generated by Django 4.1 on 2022-08-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=45, null=True)),
                ("lastname", models.CharField(blank=True, max_length=45, null=True)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("home_town", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "current_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
