# Generated by Django 4.1 on 2022-09-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0009_alter_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="applyjob",
            name="pr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
