# Generated by Django 4.1 on 2022-09-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0011_alter_employer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="fullname",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
