# Generated by Django 4.1 on 2022-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0012_applyjob_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="applyjob",
            name="email",
            field=models.EmailField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
