# Generated by Django 4.1 on 2022-09-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0013_applyjob_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                max_length=10,
                null=True,
            ),
        ),
    ]
