# Generated by Django 4.1 on 2022-09-07 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0014_alter_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
