# Generated by Django 4.1 on 2022-09-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0015_alter_applyjob_email_alter_applyjob_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="applyjob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applys",
                to="app_recuitment.job",
            ),
        ),
    ]
