# Generated by Django 4.1 on 2022-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0016_alter_applyjob_cv_alter_applyjob_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="cv",
            field=models.FileField(default=11, upload_to="documents/"),
            preserve_default=False,
        ),
    ]
