# Generated by Django 4.1 on 2022-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_recuitment", "0017_alter_applyjob_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applyjob",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
